### ISSUE TITLE
variational lower bound

### ISSUE THREAD

**Issue by yalunar** [Jianbo-Lab/L2X#1]
It seems that this question is not relevant to the codes, but may I ask why the lower bound of the conditional expectation of log Pm(Y | x) is the conditional expectation of log Qs(Y | x)? I think applying the Jensen’s inequality yields the lower bound to a function of Pm. I can't find any relationship between Pm and Qs.

**Comment by Jianbo-Lab** [comment]
Good question! I write a short proof below.

Let p=P_m(Y|x) and q=Qs(Y|x). What we want to show is 
\int (p log p) >= \int (p log q),                       (1)
where \int is a notation for integration. 

Subtracting both sides by \int p log q, it reduces to  
\int (p log p/q) >= 0.                                      (2)
That is equivalent to \int (p log q/p) <= 0.     (3)

Log is a concave function. By Jensen's inequality, we have
\int (p log q/p) <= log \int (p * q/p) = log \int q = log 1 = 0.   (4)

Another comment: It can be seen that the right hand side of equation (2) is KL-divergence of p and q. What we'd like to show is equivalent to the statement that KL-divergence is non-negative.

**Comment by yalunar** [comment]
Wow, I got it. Thanks a lot for your awesome explanation !!!
