### ISSUE TITLE
3D convolutional Neural Network

### ISSUE THREAD

**Issue by xuzhang5788** [Jianbo-Lab/L2X#2]
Can it explain 3D convolutional NN for 3D images classification? Thanks.

**Comment by Jianbo-Lab** [comment]
It can explain 3D images in theory, although I haven't tried that in practice.

Depending on what you want as a single feature, you can design the explanation network that assigns weight on each part. For example, one can divide a 3D image into cubes, and take each cube as a single feature. Importance scores are assigned to each cube correspondingly.

**Comment by xuzhang5788** [comment]
Thank you @Jianbo-Lab.
How to deal with channels? For a 3D image, each cube has 3 channels.

**Comment by Jianbo-Lab** [comment]
Sorry for the late reply due to a busy week.

If one wants to interpret 3 channels as a single feature, what one can do is to use a common weight for all the three channels. That is, multiply a common weight for each of the three channels.
